[project]
name = "rag"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "colorlog>=6.9.0",
    "llama-index>=0.12.42",
    "llama-index-embeddings-huggingface>=0.5.4",
    "llama-index-llms-ollama>=0.6.2",
]
